   // Catálogo para la tienda
 window.catalogData = {
    products: [
      {
        id: "f1",
        name: "Figura Funko Pop: Goku",
        price: 399,
        category: "coleccionables",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZF7R8JvRjslWRkxBHV9kBr2wDCqnJ2vwf5g&s",
        stock: 20,
        description: "Figura coleccionable Funko Pop de Goku Super Saiyan.",
        rating: 4.8,
        brand: "Funko",
        tags: ["dragon ball", "anime", "coleccion"]
      },
      {
        id: "f2",
        name: "Playera Zelda",
        price: 299,
        category: "ropa",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRakuHTJ-zuCVLWqQHM3IiA7b_7_T7Lnf1cJA&s",
        stock: 35,
        description: "Playera con diseño de The Legend of Zelda.",
        rating: 4.6,
        brand: "Nintendo",
        tags: ["zelda", "videojuegos", "ropa"]
      },
      {
        id: "f3",
        name: "Manga: Naruto Vol. 1",
        price: 249,
        category: "lectura",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWrWl8sLxB-wlmDfSV48_9-BE96Y3DssO4ENP5tOwE9Q&s",
        stock: 15,
        description: "Primer volumen del manga clásico Naruto.",
        rating: 4.9,
        brand: "Shueisha",
        tags: ["manga", "naruto", "anime"]
      },
      {
        id: "f4",
        name: "Mouse Gamer RGB",
        price: 899,
        category: "electronicos",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqsruVjBHeDsfy028TV3t74iVNiCMI0lQNaw&s",
        stock: 25,
        description: "Mouse gamer con luces RGB y alta precisión.",
        rating: 4.7,
        brand: "Razer",
        tags: ["gaming", "pc", "rgb"]
      },
      {
        id: "f5",
        name: "Sudadera Star Wars",
        price: 699,
        category: "ropa",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBXBBmC3GyRRY4jdInPDpYK4Y5X_tjjjX77w&s",
        stock: 30,
        description: "Sudadera con diseño clásico de Star Wars.",
        rating: 4.5,
        brand: "Disney",
        tags: ["star wars", "ropa", "friki"]
      },
      {
        id: "f6",
        name: "Poster Spiderman",
        price: 199,
        category: "decoracion",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzNCNwQC3o9F0JJgSqwZN9X6_d_fQVXNYpaQ&s",
        stock: 40,
        description: "Poster de spiderman",
        rating: 4.4,
        brand: "Kodansha",
        tags: ["superheroes", "poster", "decoracion"]
      },
      {
        id: "f7",
        name: "Control Retro NES",
        price: 499,
        category: "electronicos",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFRMTF2M0rvNLYTMmXkOyqdPS-0RUl0GDEv_5K0gd1Dg&s",
        stock: 18,
        description: "Control clásico estilo NES compatible con PC.",
        rating: 4.3,
        brand: "RetroTech",
        tags: ["retro", "nintendo", "gaming"]
      },
      {
        id: "f8",
        name: "Libro: Historia de Marvel",
        price: 599,
        category: "lectura",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxq9OGpVpIVR71E8zRLcNWuoi4rMkkbvgh8iNvaQr2tA&s",
        stock: 10,
        description: "Libro ilustrado sobre la historia de Marvel Comics.",
        rating: 4.7,
        brand: "Marvel",
        tags: ["cómics", "marvel", "lectura"]
      },
      {
        id: "f9",
        name: "Figura Funko Pop: Ichigo kurosaki",
        price: 429,
        category: "coleccionables",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZeVnJus3ndrkGwAVKOvNAEZggNTmT1qnptw&s",
        stock: 22,
        description: "Funko Pop del icónico Ichigo kurosaki con su catana",
        rating: 4.9,
        brand: "Funko",
        tags: ["bleach", "coleccionables", "funko"]
      },
      {
        id: "f10",
        name: "Playera Pokémon Pikachu",
        price: 279,
        category: "ropa",
        image: "https://m.media-amazon.com/images/I/51M2VAqmujL._AC_.jpg",
        stock: 40,
        description: "Playera amarilla con diseño de Pikachu.",
        rating: 4.6,
        brand: "Nintendo",
        tags: ["pokemon", "ropa", "anime"]
      },
      {
        id: "f11",
        name: "Manga: One Piece Vol. 1",
        price: 249,
        category: "lectura",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnIARN0hbf2DX54Ps2TKIK7XIIL3klZqV23w&s",
        stock: 20,
        description: "Primer volumen del manga One Piece de Eiichiro Oda.",
        rating: 4.9,
        brand: "Shueisha",
        tags: ["manga", "one piece", "anime"]
      },
      {
        id: "f12",
        name: "Teclado Gamer Mecánico RGB",
        price: 1299,
        category: "electronicos",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkDutfQOIzsXZZirY0cCSX8kJdpqA1GdeoBA&s",
        stock: 15,
        description: "Teclado mecánico con retroiluminación RGB personalizable.",
        rating: 4.8,
        brand: "HyperX",
        tags: ["gaming", "pc", "rgb"]
      },
      {
        id: "f13",
        name: "Lámpara 3D Dragon Ball",
        price: 349,
        category: "decoracion",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYfwfNUCZOgr3yX1a5k0bNYiRiuttRuhEw1w&s",
        stock: 28,
        description: "Lámpara 3D con diseño de esfera del dragón.",
        rating: 4.6,
        brand: "AnimeLights",
        tags: ["dragon ball", "decoración", "anime"]
      },
      {
        id: "f14",
        name: "Poster Bat-man",
        price: 189,
        category: "decoracion",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPQ4AD_SQjjA4zTfDFf1occWQ9kBf89cu5wl93Mues_w&s",
        stock: 35,
        description: "Poster del clásico héroe Spider-Man.",
        rating: 4.5,
        brand: "DC",
        tags: ["DC", "poster", "cómics"]
      },
      {
        id: "f15",
        name: "Control Inalámbrico  ",
        price: 549,
        category: "electronicos",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNWAO4s-tpV9u9wZYeGNuCiJESatXsRJEUEw&s",
        stock: 18,
        description: "Control inalámbrico  Switch.",
        rating: 4.4,
        brand: "RetroBit",
        tags: ["retro", "gaming", "nintendo"]
      },
      {
        id: "f16",
        name: "Sudadera Hogwarts",
        price: 649,
        category: "ropa",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcrqbvmbFjKyNNCvok-Gk-AaRQMhgyQGwOTQ&s",
        stock: 25,
        description: "Sudadera con el escudo de Hogwarts.",
        rating: 4.7,
        brand: "Warner Bros",
        tags: ["harry potter", "ropa", "magia"]
      },
      {
        id: "f17",
        name: "Figura articulada: Iron Man",
        price: 799,
        category: "coleccionables",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8xuOMmlV_ewd5dR_xvwPV8NXTix4HxNmQ22ZIbYWLZA&s",
        stock: 12,
        description: "Figura articulada de Iron Man con detalle metálico.",
        rating: 4.8,
        brand: "Hasbro",
        tags: ["marvel", "coleccionables", "iron man"]
      },
      {
        id: "f18",
        name: "Libro: El señor de los anillos",
        price: 520,
        category: "lectura",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTZ_5S-KOicVTLPLG_61suK5GwfCeEW2olR4GnEBzSyQ&s",
        stock: 14,
        description: "Libro del señor de los anillos",
        rating: 4.7,
        brand: "Minotauro",
        tags: ["El señor de los anilos", "lectura", "fantasía"]
      },
      
    {
      id: "f19",
      name: "Figura Funko Pop: Tanjiro Kamado",
      price: 429,
      category: "coleccionables",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcGAQl5n2Hq-cpbC3bY8fXzec77nH8gvX2qQ&s",
      stock: 22,
      description: "Funko Pop de Tanjiro con katana.",
      rating: 4.8,
      brand: "Funko",
      tags: ["demon slayer", "anime", "figura"]
    },
    {
      id: "f20",
      name: "Playera Attack on Titan",
      price: 299,
      category: "ropa",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmF6_SctSGpapaaiLS8PIfa80KBDhLLDWJFQ&s",
      stock: 30,
      description: "Playera con el emblema de la Legión de Reconocimiento.",
      rating: 4.7,
      brand: "Kodansha",
      tags: ["aot", "ropa", "anime"]
    },
    {
      id: "f21",
      name: "Manga: Jujutsu Kaisen Vol. 1",
      price: 249,
      category: "lectura",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQun0XHfc3_IA8pkGSZMXSZMazFd5og2RFxBQ&s",
      stock: 16,
      description: "Primer volumen del manga Jujutsu Kaisen.",
      rating: 4.9,
      brand: "Shueisha",
      tags: ["manga", "jjk", "anime"]
    },
    {
      id: "f22",
      name: "Audífonos Gamer RGB",
      price: 699,
      category: "electronicos",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRapxTtipx6g7zoiDhFYc3vfmk27mn4Piv1Nw&s",
      stock: 20,
      description: "Audífonos gamer con luces RGB y micrófono.",
      rating: 4.5,
      brand: "Redragon",
      tags: ["gaming", "pc", "rgb"]
    },
    {
      id: "f23",
      name: "Poster Demon Slayer",
      price: 179,
      category: "decoracion",
      image:  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2767b8iAt4TwNMyqr4HPI5qlOgckPinDj_w&s",
      stock: 40,
      description: "Poster con ilustración de los cazadores de demonios.",
      rating: 4.6,
      brand: "AnimeArt",
      tags: ["decoración", "anime", "demon slayer"]
    },
    {
      id: "f24",
      name: "Control Inalámbrico PS4",
      price: 899,
      category: "electronicos",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwsKvHy558iBh_Mww3ghhV8lLZImxP95jc6g&s",
      stock: 22,
      description: "Control inalámbrico compatible con PlayStation 4.",
      rating: 4.6,
      brand: "Sony",
      tags: ["gaming", "ps4", "control"]
    },
    {
      id: "f25",
      name: "Colección Stickers Anime",
      price: 120,
      category: "decoracion",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQEDWOs1J7XmNfD8VK5CtvBXrG7Rmk-fafgg&s",
      stock: 50,
      description: "Paquete con 100 stickers temáticos de anime.",
      rating: 4.7,
      brand: "OtakuPack",
      tags: ["stickers", "anime", "decoración"]
    },
    {
      id: "f26",
      name: "Sudadera Naruto Clan Uchiha",
      price: 649,
      category: "ropa",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLwj1RbJXecJpeUjfC7wvlnUye6eErmM2KXg&s",
      stock: 25,
      description: "Sudadera con el símbolo del clan Uchiha.",
      rating: 4.8,
      brand: "Shueisha",
      tags: ["naruto", "ropa", "anime"]
    },
    {
      id: "f27",
      name: "Manga: Chainsaw Man Vol. 1",
      price: 249,
      category: "lectura",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTidWla2TPd7iYdajmb1ik4nS0wCsX2Ozo-hQ&s",
      stock: 14,
      description: "Volumen 1 del manga Chainsaw Man.",
      rating: 4.9,
      brand: "Shueisha",
      tags: ["csm", "manga", "anime"]
    },
    {
      id: "f28",
      name: "Figura articulada: Luffy Gear 5",
      price: 799,
      category: "coleccionables",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJF0ljHGdW14_sxAJdf4O-aJlBRNQ8o9xjMQ&s",
      stock: 10,
      description: "Figura detallada de Monkey D. Luffy Gear 5.",
      rating: 4.9,
      brand: "Banpresto",
      tags: ["one piece", "coleccionables", "luffy"]
    },
    {
      id: "f29",
      name: "Lámpara 3D Pokémon Pokebola",
      price: 329,
      category: "decoracion",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEl3RFG2qc_1wOkWkILPsf0GA3YN0Kj2Te4A&s",
      stock: 33,
      description: "Lámpara 3D con forma de Pokebola.",
      rating: 4.6,
      brand: "AnimeLights",
      tags: ["pokemon", "luz", "decoración"]
    },
    {
      id: "f30",
      name: "Mouse Pad XXL Anime",
      price: 299,
      category: "decoracion",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRly1rFsGFlE-YzwQQaITw1M6FcgkXOvSGnXg&s",
      stock: 40,
      description: "Mouse pad grande con ilustración anime.",
      rating: 4.7,
      brand: "OtakuGear",
      tags: ["gaming", "anime", "pc"]
    },
    {
      id: "f31",
      name: "Playera One Piece Sombrero de Paja",
      price: 289,
      category: "ropa",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4Qk3N79Ccwe1KZo9iHZVgwLEgO6Zq_hzhww&s",
      stock: 36,
      description: "Playera con el símbolo del Sombrero de Paja.",
      rating: 4.7,
      brand: "Toei Animation",
      tags: ["one piece", "ropa", "anime"]
    },
    {
      id: "f32",
      name: "Teclado Compacto Gamer",
      price: 899,
      category: "electronicos",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR1SH8VmsWsgUvOCvfcWbh-HYtdacv4g-HqQ&s",
      stock: 17,
      description: "Teclado gamer compacto con teclas silenciosas.",
      rating: 4.5,
      brand: "Logitech",
      tags: ["pc", "gaming", "teclado"]
    },
    {
      id: "f33",
      name: "Figura Funko Pop: Levi Ackerman",
      price: 499,
      category: "coleccionables",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQa5ETOvBltoCpmTw0tj-6PDqLMNM_r5m6LSA&s",
      stock: 18,
      description: "Funko Pop del capitán Levi.",
      rating: 4.9,
      brand: "Funko",
      tags: ["aot", "funko", "anime"]
    },
    {
      id: "f34",
      name: "Gorra Pokémon Team Rocket",
      price: 259,
      category: "ropa",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4cIUfAQx2ZSM5DuCKkjUjAnVG3ytt2tUoww&s",
      stock: 28,
      description: "Gorra clásica con la 'R' del Equipo Rocket.",
      rating: 4.6,
      brand: "Nintendo",
      tags: ["pokemon", "ropa", "gorra"]
    },
    {
      id: "f35",
      name: "Manga: Spy x Family Vol. 1",
      price: 249,
      category: "lectura",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQGvN521h565h0maI-z4Ois4eHey2aqrnU1w&s",
      stock: 19,
      description: "Primer volumen del manga Spy x Family.",
      rating: 4.9,
      brand: "Shueisha",
      tags: ["manga", "spy x family", "anime"]
    },
    {
      id: "f36",
      name: "Audífonos Bluetooth Estilo Gato RGB",
      price: 499,
      category: "electronicos",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqYQvh8-wiQcIpuyCKLT7drhDys_aACfcP2g&s",
      stock: 30,
      description: "Audífonos RGB con diseño de orejas de gato.",
      rating: 4.7,
      brand: "KawaiiTech",
      tags: ["rgb", "bluetooth", "cute"]
    },
    {
      id: "f37",
      name: "Poster One Piece Wano",
      price: 179,
      category: "decoracion",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS16_LAadTv1BWF-5vuNAixFHcN6ZSDYtjuxw&s",
      stock: 32,
      description: "Poster de Luffy en el arco de Wano.",
      rating: 4.6,
      brand: "Toei Animation",
      tags: ["one piece", "decoración", "anime"]
    },
    {
      id: "f38",
      name: "Figura Demon Slayer: Nezuko Kamado",
      price: 540,
      category: "coleccionables",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5XAW9VkkxEUtErj20BEWPzHLCrL4X6o06QA&s",
      stock: 16,
      description: "Figura detallada de Nezuko.",
      rating: 4.8,
      brand: "Banpresto",
      tags: ["nezuko", "demon slayer", "anime"]
    },
    {
      id: "f39",
      name: "Sudadera Pokémon Charizard",
      price: 699,
      category: "ropa",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSx5O9UdBh_ImD22m79t4sLr0gHBQRCTg0NkQ&s",
      stock: 20,
      description: "Sudadera con diseño de Charizard.",
      rating: 4.7,
      brand: "Nintendo",
      tags: ["pokemon", "ropa", "charizard"]
    },
    {
      id: "f40",
      name: "Set de Plumas Anime",
      price: 89,
      category: "decoracion",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2N1OZj97DR1VQw1MHLBbF40aWs7qKdZQtjA&s",
      stock: 60,
      description: "Plumas decoradas con personajes de anime.",
      rating: 4.5,
      brand: "OtakuDesk",
      tags: ["plumas", "anime", "útiles"]
    },
    {
      id: "f41",
      name: "Figura Funko Pop: Batman",
      price: 429,
      category: "coleccionables",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToxUL_JJeldGHh_7BxFc1yBE42sIXduKaH9g&s",
      stock: 20,
      description: "Funko Pop del Caballero Oscuro.",
      rating: 4.8,
      brand: "Funko",
      tags: ["dc", "batman", "coleccion"]
    },
    {
      id: "f42",
      name: "Libro: Star Wars La Alta República",
      price: 420,
      category: "lectura",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTz7DxoqcqV_iRDIYmGDgGrpc_zf4lE71yHTg&s",
      stock: 13,
      description: "Novela del universo Star Wars.",
      rating: 4.6,
      brand: "Disney Books",
      tags: ["star wars", "lectura"]
    },
    {
      id: "f43",
      name: "Mouse Gamer Honeycomb",
      price: 690,
      category: "electronicos",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQecpMYmtl-fS7qEDcrO-CyNe4ESCIC1GaEQ&s",
      stock: 18,
      description: "Mouse ultra ligero estilo honeycomb.",
      rating: 4.7,
      brand: "Glorious",
      tags: ["gaming", "pc", "mouse"]
    },
    {
      id: "f44",
      name: "Playera Marvel Avengers",
      price: 329,
      category: "ropa",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_JWO32l-ZTCG22KR0cO8Q3lPkO4lZuzSzXA&s",
      stock: 28,
      description: "Playera con los Vengadores.",
      rating: 4.6,
      brand: "Marvel",
      tags: ["marvel", "ropa"]
    },
    {
      id: "f45",
      name: "Poster Stranger Things",
      price: 189,
      category: "decoracion",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzFztehPIcD7nDKqBk_HbJaUCDXNSSFkDOkQ&s",
      stock: 38,
      description: "Poster de Stranger Things.",
      rating: 4.5,
      brand: "Netflix",
      tags: ["series", "poster"]
    },
    {
      id: "f46",
      name: "Figura articulada: Spider-Man",
      price: 759,
      category: "coleccionables",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTh-yiBxvp52T61QN3gga1rms3WqMHfy7Q2jw&s",
      stock: 12,
      description: "Figura premium de Spider-Man.",
      rating: 4.8,
      brand: "Hasbro",
      tags: ["marvel", "spiderman"]
    },
    {
      id: "f47",
      name: "Manga: Tokyo Revengers Vol. 1",
      price: 230,
      category: "lectura",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzCs1bZX9DJhAE7BNcXbOYmoOH8sZedJQffg&s",
      stock: 20,
      description: "Primer volumen de Tokyo Revengers.",
      rating: 4.8,
      brand: "Kodansha",
      tags: ["manga", "tokyo revengers"]
    },
    {
      id: "f48",
      name: "Lámpara 3D Zelda Trifuerza",
      price: 360,
      category: "decoracion",
      image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTEAmvF77YfDQ7mJENV-lh376x9nDBbmRKkqTNSYu4AxNmY0Fdbtue49FkASHhfbjExbtYn99l8AN9uFdqDqZeyKt2gh8LPdVqXWVkqaKHIT-jGmGDP-wVw2i7n8OaqMhSpCY6mIw&usqp=CAc",
      stock: 22,
      description: "Lámpara con el símbolo de la Trifuerza.",
      rating: 4.8,
      brand: "Nintendo",
      tags: ["zelda", "luz"]
    },
    {
      id: "f49",
      name: "Hoodie Cyberpunk",
      price: 720,
      category: "ropa",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvwBrSpTeuxcgLxtsAYKa--4VMC79OBOCl3A&s",
      stock: 24,
      description: "Sudadera con diseño futurista.",
      rating: 4.7,
      brand: "CyberStyle",
      tags: ["cyberpunk", "ropa"]
    },
    {
      id: "f50",
      name: "Control Inalámbrico Xbox",
      price: 1299,
      category: "electronicos",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvmXAfC1T6WWwItc1voDzmWyoJgUfKH00v_g&s",
      stock: 18,
      description: "Control original Xbox Series.",
      rating: 4.8,
      brand: "Microsoft",
      tags: ["xbox", "gaming"]
    },
    {
      id: "f51",
      name: "Mouse Pad RGB",
      price: 350,
      category: "electronicos",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAWVBMAIvNHLtWyrH3qJWJ5Byiud4dcx4hGQ&s",
      stock: 32,
      description: "Base para mouse con iluminación RGB.",
      rating: 4.6,
      brand: "Razer",
      tags: ["pc", "rgb"]
    },
    {
      id: "f52",
      name: "Libro: Dune",
      price: 490,
      category: "lectura",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-zAh0q8KPZ6XMrPWEug7ww1BW4iXJl83woA&s",
      stock: 10,
      description: "Edición especial del clásico Dune.",
      rating: 4.9,
      brand: "Minotauro",
      tags: ["dune", "lectura"]
    },
    {
      id: "f53",
      name: "Poster The Witcher",
      price: 189,
      category: "decoracion",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBIflDUltxzI0v5qaAlzrH6UV9DvYaUzKaXQ&s",
      stock: 33,
      description: "Poster inspirado en The Witcher.",
      rating: 4.5,
      brand: "Netflix",
      tags: ["the witcher", "poster"]
    },
    {
      id: "f54",
      name: "Figura Funko Pop: Harry Potter",
      price: 410,
      category: "coleccionables",
      image: "https://i.ebayimg.com/images/g/OT8AAOSwvaNkrXLw/s-l400.jpg",
      stock: 20,
      description: "Funko Pop de Harry Potter con varita.",
      rating: 4.7,
      brand: "Funko",
      tags: ["harry potter", "coleccionables"]
    },
    {
      id: "f55",
      name: "Playera Minecraft Creeper",
      price: 299,
      category: "ropa",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQN1OvCEZfliAbT21kUIdlOqAsnqSQnP7U0NQ&s",
      stock: 38,
      description: "Playera verde con diseño de Creeper.",
      rating: 4.6,
      brand: "Mojang",
      tags: ["minecraft", "ropa"]
    },
    {
      id: "f56",
      name: "Manga: My Hero Academia Vol. 1",
      price: 240,
      category: "lectura",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_UV4-U26oCxtkxXa8bI8q4o4tNaxC4fWZwg&s",
      stock: 21,
      description: "Primer tomo de Boku no Hero Academia.",
      rating: 4.8,
      brand: "Shueisha",
      tags: ["manga", "boku no hero"]
    },
    {
      id: "f57",
      name: "Audífonos Gamer PS5",
      price: 1099,
      category: "electronicos",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMINCI_d7B9t1nt3_YhqEuoFkBXE6c-5scjw&s",
      stock: 14,
      description: "Audífonos inalámbricos compatibles con PS5.",
      rating: 4.7,
      brand: "Sony",
      tags: ["ps5", "audio"]
    },
    {
      id: "f58",
      name: "Lámpara 3D Mario Question Block",
      price: 399,
      category: "decoracion",
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlc_uyN2Q7fDhK5u6GAr0aHTM3GJ0sEK9inw&s",
      stock: 29,
      description: "Lámpara en forma de bloque de Mario.",
      rating: 4.8,
      brand: "Nintendo",
      tags: ["mario", "decoración", "gaming"]
    }

    ]
  };
  